### ISSUE TITLE
RabbitMQ version wired into the terraform config is no longer available on CloudAMQP

### ISSUE THREAD

**Issue by saelkind** [confluentinc/demo-database-modernization#24]
The configuration in main.tf needs to be updated - the version wired into the config is 3.12.1, which is no longer available on CloudAMQP:

`│ Error: CreateInstance failed, status: 400, message: map[errors:[map[rmq_version:Invalid RabbitMQ version, available versions are ["3.9.8", "3.9.9", "3.9.11", "3.9.13", "3.9.15", "3.9.16", "3.9.18", "3.9.19", "3.9.20", "3.9.21", "3.9.22", "3.9.23", "3.9.27", "3.10.1", "3.10.2", "3.10.4", "3.10.5", "3.10.6", "3.10.7", "3.10.8", "3.10.10", "3.10.19", "3.10.24", "3.11.5", "3.11.10", "3.11.18", "3.12.2", "3.12.4"]]]]
│
│   with cloudamqp_instance.instance,
│   on main.tf line 231, in resource "cloudamqp_instance" "instance":
│  231: resource "cloudamqp_instance" "instance" {
│
╵`
After changing the value to 3.12.2, it was able to created the RabbitMQ instance

**Comment by mkananizadeh** [comment]
Thanks for raising the issue. I just pushed a fixed.
