### ISSUE TITLE
Suggested improvement to fraud logic in ksqldb

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/demo-database-modernization#5]
Consider this query, which captures the fraud logic of the `FD_POSSIBLE_STOLEN_CARD`:

```SQL
SELECT
        TIMESTAMPTOSTRING(WINDOWSTART, 'yyyy-MM-dd HH:mm:ss') AS WINDOW_START,
        T.USERID,
        T.CREDIT_CARD_NUMBER,
        T.FULL_NAME,
        T.EMAIL,
        T.TRANSACTION_TIMESTAMP,
        SUM(T.AMOUNT) AS TOTAL_CREDIT_SPEND,
        MAX(T.AVG_CREDIT_SPEND) AS AVG_CREDIT_SPEND,
        COUNT(*) AS NUM_TRANSACTIONS
    FROM fd_transactions_enriched T
    WINDOW TUMBLING (SIZE 2 HOURS)
    GROUP BY T.USERID, T.CREDIT_CARD_NUMBER, T.FULL_NAME, T.EMAIL, T.TRANSACTION_TIMESTAMP
    HAVING SUM(T.AMOUNT) > MAX(T.AVG_CREDIT_SPEND) EMIT CHANGES;
```

The `GROUP BY` clause is grouping so many different things that there really is no aggregation going on. You can verify that `NUM_TRANSACTIONS` is always 1.

I believe this formulation was a workaround for this error when only grouping by id:

```
Non-aggregate SELECT expression(s) not part of GROUP BY:
CREDIT_CARD_NUMBER, FULL_NAME, EMAIL, TRANSACTION_TIMESTAMP Either add the column(s) to the GROUP BY or remove them from the SELECT.
```

This comes from creating the customers table with `LATEST_BY_OFFSET` (see [issue](https://github.com/confluentinc/ksql/issues/5114))

## Proposal

Instead of creating a raw customer stream and using `LATEST_BY_OFFSET` to derive a table, create a table directly from the underlying topic:
```SQL
CREATE TABLE FD_CUSTOMERS (
  customer_id DOUBLE PRIMARY KEY
  ) WITH (KAFKA_TOPIC = 'ORCL.ADMIN.CUSTOMERS',KEY_FORMAT='JSON',VALUE_FORMAT = 'JSON_SR');
```
> NOTE: We avoid the error "column name id already exists" by giving the key a different name, customer_id.

Then create the enriched transaction stream.

```SQL
CREATE STREAM fd_transactions_enriched WITH (KAFKA_TOPIC = 'transactions_enriched') AS
  SELECT
    C.CUSTOMER_ID,
    T.CREDIT_CARD_NUMBER,
    T.AMOUNT,
    T.TRANSACTION_TIMESTAMP,
    C.FIRST_NAME + ' ' + C.LAST_NAME AS FULL_NAME,
    C.AVG_CREDIT_SPEND,
    C.EMAIL
  FROM fd_transactions T
  INNER JOIN fd_customers C
  ON T.USERID = C.CUSTOMER_ID;
```

Then create the fraud trigger only grouping by things that we want to count as a group, in this case customer ID, avg spend, full name, email:

```SQL
CREATE TABLE fd_possible_stolen_card WITH (KAFKA_TOPIC = 'FD_possible_stolen_card', KEY_FORMAT = 'JSON', VALUE_FORMAT='JSON') AS
SELECT
  T.CUSTOMER_ID,
  LATEST_BY_OFFSET(T.TRANSACTION_TIMESTAMP) AS LATEST_TIMESTAMP,
  COUNT(*) AS NUM_TRANSACTIONS,
  T.FULL_NAME,
  LATEST_BY_OFFSET(T.EMAIL) AS EMAIL,
  SUM(T.AMOUNT) AS TOTAL_CREDIT_SPEND,
  T.AVG_CREDIT_SPEND,
  TIMESTAMPTOSTRING(WINDOWSTART, 'yyyy-MM-dd HH:mm:ss') AS WINDOW_START
FROM FD_TRANSACTIONS_ENRICHED T
WINDOW TUMBLING ( SIZE 2 HOURS ) 
GROUP BY T.CUSTOMER_ID, T.AVG_CREDIT_SPEND, T.FULL_NAME, T.EMAIL
HAVING (SUM(T.AMOUNT) > T.AVG_CREDIT_SPEND);
```
Notice the `LATEST_BY_OFFSET(T.EMAIL)` -- this means if a user changes their email address, it won't reset the aggregation.

**Comment by chuck-confluent** [comment]
We probably also want to group by credit card, but for that to work, we would need to modify the transaction generator script so that each person has a static set of 1-2 credit cards and always use one of those cards for a given person.

Also, the transaction amounts are so high that everyone is going to get fraud alerts (because we would now be summing over ~60 transactions per 2 hrs). We would need to tune the dollar value of each transaction so not everyone gets an alert. With 1 transaction per second, that's 60 txns per minute, spread over 20 people, so that's 3 txns per minute per person, on average. Over 2hrs, that's 3 txns/min/person * 60 min/hr * 2 hrs/window = 360 txns/person per window. If we make each transaction $10 on average, then folks whose avg spend is less than 360*10 = $3600 will get fraud alerts (although it will take 2 hrs to get the alert). We may want to have a handful of folks who always have higher transaction amounts so they get fraud alerts faster. If each person has 2 credit cards, we would also need to double the transaction amounts or ensure that, say, the first card is "hotter" than the second.

**Comment by chuck-confluent** [comment]
- We should also use JSON_SR or AVRO schema for the transaction_enriched topic when creating the stream. More schema the better.
- Also the possible stolen cards topic should have schema and set `input.data.format` to `AVRO` for the mongo sink.

**Comment by mkananizadeh** [comment]
Pushed to v2.0
